version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/MicaWPF"
    schedule:
      interval: "daily"
    reviewers:
      - "Simnico99"

  - package-ecosystem: "nuget"
    directory: "/src/MicaWPF.Core"
    schedule:
      interval: "daily"
    reviewers:
      - "Simnico99"

  - package-ecosystem: "nuget"
    directory: "/src/MicaWPF.Lite"
    schedule:
      interval: "daily"
    reviewers:
      - "Simnico99"

  - package-ecosystem: "nuget"
    directory: "/src/MicaWPF.DependencyInjection"
    schedule:
      interval: "daily"
    reviewers:
      - "Simnico99"
