name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "Needs-Triage"]
assignees:
  - Simnico99
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      multiple: true
      options:
        - "Insider Build (xxxxx)"
        - "Windows 11 version 23H2 (22631, 2023 Update)"
        - "Windows 11 version 22H2 (22621, 2022 Update)"
        - "Windows 11 version 21H2 (22000)"
        - "Windows 10 version 22H2 (19045, 2022 Update)"
        - "Windows 10 version 21H2 (19044, November 2021 Update)"
        - "Windows 10 version 21H1 (19043, May 2021 Update)"
        - "Windows 10 version 20H2 (19042, October 2020 Update)"
        - "Windows 10 version 2004 (19041, May 2020 Update)"
        - "Windows 10 version 1909 (18363, November 2019 Update)"
        - "Windows 10 version 1903 (18362, May 2019 Update)"
        - "Windows 10 version 1809 (17763, October 2018 Update)"
        - "Other (Please add the version in additionnal context.)"
  - type: dropdown
    validations:
      required: true
    attributes:
      label: .Net Version
      description: Which Version of .Net are you using?
      multiple: true
      options:
        - ".Net Framework 4.6.x"
        - ".Net Framework 4.7.x"
        - ".Net Framework 4.8.x"
        - ".NET Standard 1.x"
        - ".NET Standard 2.x"
        - ".NET Core 1.x"
        - ".NET Core 2.x"
        - ".NET Core 3.x"
        - ".NET 5.x"
        - ".NET 6.x"
        - ".NET 7.x"
        - ".NET 8.x"        
        - "Other (Please add the version in additionnal context.)"
  - type: dropdown
    validations:
      required: true
    attributes:
      label: .MicaWPF Version
      description: Which version lite or not of MicaWPF you are using?
      multiple: true
      options:
        - "MicaWPF"
        - "MicaWPF.Lite"    
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
